---
title: "Help yourself: Assignment 4"
author:
  - name: "Michael McCarthy"
    url: https://github.com/mccarthy-m-g
    affiliation: "PSYC 615 Lab"
    affiliation_url: https://github.com/mccarthy-m-g/psyc-615-lab
repository_url: https://github.com/mccarthy-m-g/psyc-615-lab
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", collapse = TRUE)
```

## Prerequisites

To access the datasets, help pages, and functions that we will use in this *help yourself*, load the following packages:

```{r prerequisites}
here::i_am("labs/05_factorial-anova/help-yourself_assignment-4.Rmd")

library(here)
library(tidyverse)
library(ggpubr)

```

As well as this Help Yourself's example data:

```{r example-data}
pain <- readr::read_csv(here::here("data", "help-yourself_a4.csv"))
```

## Simulating data sets part 2

show them faux package
https://debruine.github.io/faux/index.html

## Learning more

Interaction analysis in emmeans <https://cran.r-project.org/web/packages/emmeans/vignettes/interactions.html>
